### ISSUE TITLE
Match DefiLlama yields

### ISSUE THREAD

**Issue by 0xsign** [llamafolio/llamafolio-api#626]
`https://yields.llama.fi/poolsOld` returns the list of yields per pool but the data doesn't always contain a smart contract address nor matches one of our contracts.

Let's look at this data and try to map it as much as possible to our protocols contracts. For instance if the protocol + chain matches and the pool has the same underlyings we can probabyl match

**Comment by o-az** [comment]
Some changes may be coming to this so it's on pause right now. Awaiting further details.

**Comment by o-az** [comment]
completed implementation. Pending review
