### ISSUE TITLE
Fix: investigate aave-v3 missing balances

### ISSUE THREAD

**Issue by 0xsign** [llamafolio/llamafolio-api#674]
`0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50` aave-v3 balances are missing on ethereum (working on avalanche)

**Comment by 0xpeluche** [comment]
Seems to be an interaction issue as we can see on this SS, its working with **`0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`**
**`pnpm run adapter aave-v3 ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`**

![aave-v3](https://github.com/llamafolio/llamafolio-api/assets/110820448/69a037da-afb2-4a3b-b734-8299544d85fe)
