### ISSUE TITLE
NFT: Integration

### ISSUE THREAD

**Issue by o-az** [llamafolio/llamafolio-api#724]
- [x] Use 3rd party API initially,
- [x] Filter scam NFTs (use API that has filters, plenty do)
- [x] Group NFTs by collection using DefiLlama API [defillama.com/nfts](https://defillama.com/nfts)
- [x] #729
- [ ] #736
- [x] market data per collection,

**Comment by 0xsign** [comment]
Group NFTs by collection using DefiLlama API

https://defillama.com/nfts

**Comment by 0xOno** [comment]
Following our discussion @o-az here's a list of what ideally we would like to be displayed. Let me know what's possible or not of course!
Collection level:
- floor price + value in USD
- number of NFT in this particular collection
- Network

NFT owned level:
- NFT number
- last sale price
- Est value (% change from last sale)
- Rarity
- Properties/abilities
- History

Thank you

**Comment by o-az** [comment]
- > Following our discussion @o-az here's a list of what ideally we would like to be displayed for each address. Let me know what's possible or not of course! Collection level:
> 
> * NFT total Value
> * floor price + value in USD
> * number of NFT in this particular collection
> * Network
> 
> NFT owned level:
> 
> * NFT number
> * last sale price
> * Est value (% change from last sale)
> * Rarity
> * Properties/abilities
> * History
> 
> Thank you


- Total value of all NFTs in USD
- quantity (total nfts owned across all collections)
	- collections:
	  - quantity (total nfts owned in this collection)
	  - network
	  - type (ERC721 | ERC1155)
	  - media (image/gif/vid)
	  - description
	  - address
	  - website
	  - name
	  - nfts
	    - address
	    - name
	    - tokenId
	    - description
	    - media (image/gif/vid)
	    - estimatedValue
	    - rarity
	    - traits
	    - history
	    - quantity (how many of this particular nft user owns)
